name: SurveyEnvironment
components:
  relation:
    plugin:
      EasyRelationPlugin:
        relations: 'agents_relation'
  space:
    plugin:
      EasySpacePlugin:
        agents: 'map_agents'
  status:
    plugin:
      EasyStatusPlugin:
        statuses: 'agent_statuses'
  survey:
    plugin:
      RegionalSurveyPlugin: {}
